import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./_components/Header";
import { CartProvider } from "./context/CartContext";
import { FavoritesProvider } from "./context/FavoritesContext";
import { ToastProvider } from "./context/ToastContext";

const InterFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${InterFont.className} antialiased`}>
        <HeaderComponent />
        <main className="container mx-auto bg-gray-100">
          <CartProvider>
            <FavoritesProvider>
              <ToastProvider>{children}</ToastProvider>
            </FavoritesProvider>
          </CartProvider>
        </main>
      </body>
    </html>
  );
}
